version: 2
# 2.1 does not yet support local run
# unless with workaround. For simplicity just use it.
# https://github.com/CircleCI-Public/circleci-cli/issues/79

aliases:
  - &defaults
    docker:
      - image: circleci/node:10

  - &npm_install_if_necessary
    run:
      name: Install npm dependencies
      command: |
        if [ ! -d node_modules ]; then
          npm ci
        fi

  - &cache_key_node_modules
    key: v1-node_modules-{{ checksum "package-lock.json" }}

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_node_modules
      - *npm_install_if_necessary
      - save_cache:
          paths:
            - node_modules
          <<: *cache_key_node_modules

  compile:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_node_modules
      - *npm_install_if_necessary
      - run:
          name: Compile
          command: npm run compile
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_node_modules
      - *npm_install_if_necessary
      - run:
          name: Unit tests
          command: npm run test

workflows:
  version: 2
  everything:
    jobs:
      - dependencies
      - compile:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
            - compile
